enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
cli-source = "MorpheApp/morphe-cli"
# cli-source = "MorpheApp/morphe-cli"
patches-source = "wchill/rvx-morphed"
#patches-source = "MorpheApp/morphe-patches"
rv-brand = "Morphe"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = true
arch = "arm64-v8a"
excluded-patches = ""
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# patcher-args = "-e 'Custom branding name for YouTube' -OappName='YouTube' -e 'Custom branding icon for YouTube' -OappIcon='youtube' -e 'Hide shortcuts' -Oexplore=true -Osubscriptions=true -Osearch=true -e 'Custom header for YouTube' -OcustomHeader='custom_branding_icon'" #-e 'MaterialYou' -Ouse=true

[YouTube-Music]
enabled = true
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon='youtube_music' -e 'Custom branding name for YouTube Music' -OappNameNotification='YT MUSIC' -OappNameLauncher='YT MUSIC' -e 'Custom header for YouTube Music' -OcustomHeader='custom_branding_icon' -e 'Disable music video in album' -Ouse=true"


